

import image4069LE from '../assets/kelim/4069LE.png';
import image10E from '../assets/kelim/10E.png';
import image120AETJ from '../assets/kelim/120AETJ.png';
import image1230ES from '../assets/kelim/1230ES.png';
import image150AETJ from '../assets/kelim/150AETJ.png';
import image170AETJ from '../assets/kelim/170AETJ.png';
import image260MRT from '../assets/kelim/260MRT.png';
import image460SJ from '../assets/kelim/460SJ.png';
import image1350 from '../assets/kelim/1350.png';
import imageGR15 from '../assets/kelim/GR15.png';
import imageGR20 from '../assets/kelim/GR20.png';
import imageGS1330 from '../assets/kelim/GS1330.png';
import imageGS1930 from '../assets/kelim/GS1930.png';
import imageGS2032 from '../assets/kelim/GS2032.png';
import imageGS2632 from '../assets/kelim/GS2632.png';
import imageGS3232 from '../assets/kelim/GS3232.png';
import imageGS3246 from '../assets/kelim/GS3246.png';
import imageGS3384RT from '../assets/kelim/GS3384RT.png';
import imageGS4047 from '../assets/kelim/GS4047.png';
import imageGS4069 from '../assets/kelim/GS4069.png';
import imageGS4069RT from '../assets/kelim/GS4069RT.png';
import imageGS5390RT from '../assets/kelim/GS5390RT.png';
import imageGTZZ15J from '../assets/kelim/GTZZ15J.png';
import imageS45 from '../assets/kelim/S45.png';
import imageS65 from '../assets/kelim/S65.png';
import imageS85 from '../assets/kelim/S85.png';
import imageSX125 from '../assets/kelim/SX125.png';
import imageZ30 from '../assets/kelim/Z30.png';
import imageZ34D from '../assets/kelim/Z34D.png';
import imageZ34E from '../assets/kelim/Z34E.png';
import imageZ45D from '../assets/kelim/Z45D.png';
import imageZ45E from '../assets/kelim/Z45E.png';
import imageZ51 from '../assets/kelim/Z51.png';
import imageZ60 from '../assets/kelim/Z60.png';
import imageZ80 from '../assets/kelim/Z80.png';



const VData = [
  {
    name: '1230ES',
    vehicleType: 'במת יחיד',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '5.60',
    liftStrenght: '0.227',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'JLG',
    color: '#ff773d',
    image: image1230ES,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/1230ES.pdf',
    description: 'Electric single platform lift suitable for all locations with a work height of 5.60 meters.',
    tags: ['electric', 'single platform', 'JLG', '5.60m'],
    altText: '1230ES electric single platform lift by JLG'
  },
  {
    name: 'GR15',
    vehicleType: 'במת יחיד',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '6.50',
    liftStrenght: '0.227',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGR15,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GR15.pdf',
    description: 'Genie GR15 electric single platform lift ideal for compact spaces with a work height of 6.50 meters.',
    tags: ['electric', 'single platform', 'Genie', '6.50m'],
    altText: 'Genie GR15 electric single platform lift'
  },
  {
    name: 'GR20',
    vehicleType: 'במת יחיד',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '8.00',
    liftStrenght: '0.159',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGR20,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GR20.pdf',
    description: 'Genie GR20 electric single platform lift suitable for various indoor applications with a work height of 8.00 meters.',
    tags: ['electric', 'single platform', 'Genie', '8.00m'],
    altText: 'Genie GR20 electric single platform lift'
  },
  {
    name: '10E',
    vehicleType: 'במת תורן אנכי',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '10.00',
    liftStrenght: '0.200',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'JLG',
    color: '#ff773d',
    image: image10E,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/TOUCAN__10E.pdf',
    description: 'JLG 10E electric mast lift for versatile usage with a work height of 10.00 meters.',
    tags: ['electric', 'mast lift', 'JLG', '10.00m'],
    altText: 'JLG 10E electric mast lift'
  },
  {
    name: 'GS1330',
    vehicleType: 'במת מספריים',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '5.90',
    liftStrenght: '0.227',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS1330,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/slab-scissor-lifts-(ansi)-or-electric-and-bi-energy-lifts-(ce)/en/gs1330m_spec_2019-11-26.pdf',
    description: 'Genie GS1330 electric scissor lift for precise and safe lifting with a work height of 5.90 meters.',
    tags: ['electric', 'scissor lift', 'Genie', '5.90m'],
    altText: 'Genie GS1330 electric scissor lift'
  },
  {
    name: 'GS1930',
    vehicleType: 'במת מספריים',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '7.80',
    liftStrenght: '0.227',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS1930,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GS1932.pdf',
    description: 'Genie GS1930 electric scissor lift, perfect for indoor tasks with a work height of 7.80 meters.',
    tags: ['electric', 'scissor lift', 'Genie', '7.80m'],
    altText: 'Genie GS1930 electric scissor lift'
  },
  {
    name: 'GS2032',
    vehicleType: 'במת מספריים',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '8.00',
    liftStrenght: '0.227',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS2032,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GS2032.pdf',
    description: 'Genie GS2032 electric scissor lift suitable for all work environments with a work height of 8.00 meters.',
    tags: ['electric', 'scissor lift', 'Genie', '8.00m'],
    altText: 'Genie GS2032 electric scissor lift'
  },
  {
    name: 'GS2632',
    vehicleType: 'במת מספריים',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '9.90',
    liftStrenght: '0.227',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS2632,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GS2632.pdf',
    description: 'Genie GS2632 electric scissor lift for efficient lifting in various work locations with a height of 9.90 meters.',
    tags: ['electric', 'scissor lift', 'Genie', '9.90m'],
    altText: 'Genie GS2632 electric scissor lift'
  },
  {
    name: 'GS3246',
    vehicleType: 'במת מספריים',
    engType: 'חשמלי',
    workLocation: 'any',
    workHeight: '11.70',
    liftStrenght: '0.318',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS3246,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GS3246.pdf',
    description: 'Genie GS3246 electric scissor lift with a work height of 11.70 meters, suitable for multiple locations.',
    tags: ['electric', 'scissor lift', 'Genie', '11.70m'],
    altText: 'Genie GS3246 electric scissor lift'
  },
  {
    name: 'GS4047',
    vehicleType: 'במת מספריים',
    engType: 'חשמלי',
    workLocation: 'any',
    workHeight: '13.70',
    liftStrenght: '0.350',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS4047,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/slab-scissor-lifts-(ansi)-or-electric-and-bi-energy-lifts-(ce)/en-gb/gs-4047-product-specifications-2020.pdf?sfvrsn=30a86589_2',
    description: 'Genie GS4047 electric scissor lift, ideal for higher lifts with a work height of 13.70 meters.',
    tags: ['electric', 'scissor lift', 'Genie', '13.70m'],
    altText: 'Genie GS4047 electric scissor lift'
  },
  {
    name: '4069LE',
    vehicleType: 'במת מספריים',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '14.00',
    liftStrenght: '0.360',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'JLG',
    color: '#ff773d',
    image: image4069LE,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/4069LE.pdf',
    description: 'JLG 4069LE electric scissor lift with robust lifting capabilities and a work height of 14.00 meters.',
    tags: ['electric', 'scissor lift', 'JLG', '14.00m'],
    altText: 'JLG 4069LE electric scissor lift'
  },
  {
    name: 'GS3232',
    vehicleType: 'במת מספריים עם מייצבים',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '11.70',
    liftStrenght: '0.227',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'הכל',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS3232,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/slab-scissor-lifts-(ansi)-or-electric-and-bi-energy-lifts-(ce)/ko/gsspec_gs3232_gs3246_en-us-apac_lr.pdf?sfvrsn=a813c4f1_3',
    description: 'Genie GS3232 electric scissor lift with stabilizers for enhanced safety, with a work height of 11.70 meters.',
    tags: ['electric', 'scissor lift', 'stabilizers', 'Genie', '11.70m'],
    altText: 'Genie GS3232 electric scissor lift with stabilizers'
  },
  {
    name: 'GS4069',
    vehicleType: 'במת מספריים עם מייצבים',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '14.00',
    liftStrenght: '0.360',
    accessibility: 'אנכית',
    groundType: 'מהודק',
    groundLevel: 'הכל',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS4069,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/rough-terrain-scissor-lifts/en-sg/2022/2022-spec-sheet-gs2669rt_gs3369rt_gs4069rt-ansi-(sea).pdf?sfvrsn=912b1616_3',
    description: 'Genie GS4069 electric scissor lift with stabilizers, providing a work height of 14.00 meters.',
    tags: ['electric', 'scissor lift', 'stabilizers', 'Genie', '14.00m'],
    altText: 'Genie GS4069 electric scissor lift with stabilizers'
  },
  {
    name: '260MRT',
    vehicleType: 'במת מספריים עם מייצבים',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '9.90',
    liftStrenght: '0.560',
    accessibility: 'אנכית',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'JLG',
    color: '#ff773d',
    image: image260MRT,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/260MRT.pdf',
    description: 'JLG 260MRT powered scissor lift with stabilizers, suitable for outdoor use, and a work height of 9.90 meters.',
    tags: ['powered', 'scissor lift', 'stabilizers', 'JLG', '9.90m'],
    altText: 'JLG 260MRT powered scissor lift with stabilizers'
  },
  {
    name: 'GS3384RT',
    vehicleType: 'במת מספריים עם מייצבים',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '12.00',
    liftStrenght: '0.450',
    accessibility: 'אנכית',
    groundType: 'הכל',
    groundLevel: 'הכל',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS3384RT,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GS3384RT.pdf',
    description: 'Genie GS3384RT powered scissor lift with stabilizers for outdoor applications with a work height of 12.00 meters.',
    tags: ['powered', 'scissor lift', 'stabilizers', 'Genie', '12.00m'],
    altText: 'Genie GS3384RT powered scissor lift with stabilizers'
  },
  {
    name: 'GS4069RT',
    vehicleType: 'במת מספריים עם מייצבים',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '14.00',
    liftStrenght: '0.363',
    accessibility: 'אנכית',
    groundType: 'הכל',
    groundLevel: 'הכל',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS4069RT,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/slab-scissor-lifts-(ansi)-or-electric-and-bi-energy-lifts-(ce)/en/2022/gsspec_gs2669_rt_gs3369_rt_gs4069_rt_en-us_na_lr.pdf?sfvrsn=e477c727_3',
    description: 'Genie GS4069RT powered scissor lift with stabilizers, ideal for outdoor work with a height of 14.00 meters.',
    tags: ['powered', 'scissor lift', 'stabilizers', 'Genie', '14.00m'],
    altText: 'Genie GS4069RT powered scissor lift with stabilizers'
  },
  {
    name: 'GS5390RT',
    vehicleType: 'במת מספריים עם מייצבים',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '18.00',
    liftStrenght: '0.680',
    accessibility: 'אנכית',
    groundType: 'הכל',
    groundLevel: 'הכל',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGS5390RT,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/GS5390RT.pdf',
    description: 'Genie GS5390RT powered scissor lift with stabilizers, designed for outdoor tasks with a height of 18.00 meters.',
    tags: ['powered', 'scissor lift', 'stabilizers', 'Genie', '18.00m'],
    altText: 'Genie GS5390RT powered scissor lift with stabilizers'
  },
  {
    name: 'Z30',
    vehicleType: 'זרוע מפרקית',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '11.00',
    liftStrenght: '0.227',
    liftAccesibility: '6.30',
    accessibility: 'הכל',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ30,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/articulated-boom-lift/en/2022/zboomspec_z30_20n_z30_20n_rj_en-us_na_lrec42dc61-4a3d-4937-a372-497615db2242.pdf?sfvrsn=6db84fd1_3',
    description: 'Genie Z30 electric articulated boom lift, perfect for tight spaces, with a work height of 11.00 meters.',
    tags: ['electric', 'articulated boom lift', 'Genie', '11.00m'],
    altText: 'Genie Z30 electric articulated boom lift'
  },
  {
    name: '120AETJ',
    vehicleType: 'זרוע מפרקית',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '11.90',
    liftStrenght: '0.200',
    liftAccesibility: '7.00',
    accessibility: 'הכל',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Manitou',
    color: '#ef271b',
    image: image120AETJ,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/120AETJ.pdf',
    description: 'Manitou 120AETJ electric articulated boom lift for various tasks with a work height of 11.90 meters.',
    tags: ['electric', 'articulated boom lift', 'Manitou', '11.90m'],
    altText: 'Manitou 120AETJ electric articulated boom lift'
  },
  {
    name: 'Z34-E',
    vehicleType: 'זרוע מפרקית',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '12.50',
    liftStrenght: '0.215',
    liftAccesibility: '6.50',
    accessibility: 'הכל',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ34E,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/Z34-22N.pdf',
    description: 'Genie Z34-E electric articulated boom lift, ideal for indoor and outdoor use, with a height of 12.50 meters.',
    tags: ['electric', 'articulated boom lift', 'Genie', '12.50m'],
    altText: 'Genie Z34-E electric articulated boom lift'
  },
  {
    name: '150AETJ',
    vehicleType: 'זרוע מפרקית',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '15.00',
    liftStrenght: '0.200',
    liftAccesibility: '7.60',
    accessibility: 'הכל',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Manitou',
    color: '#ef271b',
    image: image150AETJ,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/150AETJ.pdf',
    description: 'Manitou 150AETJ electric articulated boom lift for high-reach tasks with a height of 15.00 meters.',
    tags: ['electric', 'articulated boom lift', 'Manitou', '15.00m'],
    altText: 'Manitou 150AETJ electric articulated boom lift'
  },
  {
    name: 'Z45-E',
    vehicleType: 'זרוע מפרקית',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '15.90',
    liftStrenght: '0.227',
    liftAccesibility: '7.60',
    accessibility: 'הכל',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ45E,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/Z45-25J.pdf',
    description: 'Genie Z45-E electric articulated boom lift, suitable for multiple applications with a height of 15.90 meters.',
    tags: ['electric', 'articulated boom lift', 'Genie', '15.90m'],
    altText: 'Genie Z45-E electric articulated boom lift'
  },
  {
    name: '170AETJ',
    vehicleType: 'זרוע מפרקית',
    engType: 'חשמלי',
    workLocation: 'הכל',
    workHeight: '16.90',
    liftStrenght: '0.200',
    liftAccesibility: '9.40',
    accessibility: 'הכל',
    groundType: 'מהודק',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Manitou',
    color: '#ef271b',
    image: image170AETJ,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/170AETJ.pdf',
    description: 'Manitou 170AETJ electric articulated boom lift for reaching high areas with a height of 16.90 meters.',
    tags: ['electric', 'articulated boom lift', 'Manitou', '16.90m'],
    altText: 'Manitou 170AETJ electric articulated boom lift'
  },
  {
    name: 'Z34-D',
    vehicleType: 'זרוע מפרקית',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '12.50',
    liftStrenght: '0.227',
    liftAccesibility: '6.80',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ34D,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/Z34-22N.pdf',
    description: 'Genie Z34-D powered articulated boom lift, perfect for outdoor applications with a height of 12.50 meters.',
    tags: ['powered', 'articulated boom lift', 'Genie', '12.50m'],
    altText: 'Genie Z34-D powered articulated boom lift'
  },
  {
    name: 'Z45-D',
    vehicleType: 'זרוע מפרקית',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '16.00',
    liftStrenght: '0.227',
    liftAccesibility: '7.60',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ45D,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/Z45-25J.pdf',
    description: 'Genie Z45-D powered articulated boom lift, ideal for outdoor tasks with a height of 16.00 meters.',
    tags: ['powered', 'articulated boom lift', 'Genie', '16.00m'],
    altText: 'Genie Z45-D powered articulated boom lift'
  },
  {
    name: 'GTZZ15J',
    vehicleType: 'זרוע מפרקית',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '16.70',
    liftStrenght: '0.25',
    liftAccesibility: '8.50',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageGTZZ15J,
    pdfLink: 'https://chinamotors.co.il/wp-content/uploads/2018/05/sinoboom-GTZZ15J-4p-14.5.pdf',
    description: 'Genie GTZZ15J powered articulated boom lift, perfect for high-reach tasks with a height of 16.70 meters.',
    tags: ['powered', 'articulated boom lift', 'Genie', '16.70m'],
    altText: 'Genie GTZZ15J powered articulated boom lift'
  },
  {
    name: 'Z51',
    vehicleType: 'זרוע מפרקית',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '17.60',
    liftStrenght: '0.227',
    liftAccesibility: '9.40',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ51,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/articulated-boom-lift/en-gb/2022/zboomspec_z51_30j_rt_en-gb_emear_lr.pdf?sfvrsn=220ec3c2_5',
    description: 'Genie Z51 powered articulated boom lift, suitable for outdoor work with a height of 17.60 meters.',
    tags: ['powered', 'articulated boom lift', 'Genie', '17.60m'],
    altText: 'Genie Z51 powered articulated boom lift'
  },
  {
    name: 'Z60',
    vehicleType: 'זרוע מפרקית',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '20.40',
    liftStrenght: '0.227',
    liftAccesibility: '11.00',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ60,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/Z60-34.pdf',
    description: 'Genie Z60 powered articulated boom lift, ideal for high-reach outdoor tasks with a height of 20.40 meters.',
    tags: ['powered', 'articulated boom lift', 'Genie', '20.40m'],
    altText: 'Genie Z60 powered articulated boom lift'
  },
  {
    name: 'Z80',
    vehicleType: 'זרוע מפרקית',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '25.80',
    liftStrenght: '0.227',
    liftAccesibility: '18.30',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageZ80,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/Z80-60.pdf',
    description: 'Genie Z80 powered articulated boom lift, designed for extensive outdoor reach with a height of 25.80 meters.',
    tags: ['powered', 'articulated boom lift', 'Genie', '25.80m'],
    altText: 'Genie Z80 powered articulated boom lift'
  },
  {
    name: 'S45',
    vehicleType: 'זרוע טלסקופית ישרה',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '15.70',
    liftStrenght: '0.227',
    liftAccesibility: '11.20',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageS45,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/S45.pdf',
    description: 'Genie S45 powered telescopic boom lift, perfect for reaching higher areas with a height of 15.70 meters.',
    tags: ['powered', 'telescopic boom lift', 'Genie', '15.70m'],
    altText: 'Genie S45 powered telescopic boom lift'
  },
  {
    name: '460SJ',
    vehicleType: 'זרוע טלסקופית ישרה',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '16.00',
    liftStrenght: '0.227',
    liftAccesibility: '10.20',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'JLG',
    color: '#ff773d',
    image: image460SJ,
    pdfLink: 'https://www.jlg.com/-/media/jlg/current-materials-no-password/products/americas%20-%20ansi/engine-powered-boom-lifts/telescopic-booms/400-series/docs/400-series-telescopic-boom-spec-sheet.pdf',
    description: 'JLG 460SJ powered telescopic boom lift, designed for outdoor use with a work height of 16.00 meters.',
    tags: ['powered', 'telescopic boom lift', 'JLG', '16.00m'],
    altText: 'JLG 460SJ powered telescopic boom lift'
  },
  {
    name: 'S65',
    vehicleType: 'זרוע טלסקופית ישרה',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '22.00',
    liftStrenght: '0.227',
    liftAccesibility: '17.10',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageS65,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/telescopic-booms/en-au/s-65-xc-product-specifications-2019.pdf?sfvrsn=e39b3a6b_2',
    description: 'Genie S65 powered telescopic boom lift, ideal for reaching tall structures with a height of 22.00 meters.',
    tags: ['powered', 'telescopic boom lift', 'Genie', '22.00m'],
    altText: 'Genie S65 powered telescopic boom lift'
  },
  {
    name: 'S85',
    vehicleType: 'זרוע טלסקופית ישרה',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '28.00',
    liftStrenght: '0.227',
    liftAccesibility: '23.30',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageS85,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/S85.pdf',
    description: 'Genie S85 powered telescopic boom lift, excellent for high-reach outdoor tasks with a height of 28.00 meters.',
    tags: ['powered', 'telescopic boom lift', 'Genie', '28.00m'],
    altText: 'Genie S85 powered telescopic boom lift'
  },
  {
    name: 'SX125',
    vehicleType: 'זרוע טלסקופית ישרה',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '40.00',
    liftStrenght: '0.3',
    liftAccesibility: '24.40',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'Genie',
    color: '#86bbd8',
    image: imageSX125,
    pdfLink: 'https://www.genielift.com/docs/default-source/product-specifications/telescopic-booms/en-au/sx-125-xc-product-specifications-2019.pdf?sfvrsn=8ddf32d0_2',
    description: 'Genie SX125 powered telescopic boom lift for extensive reach with a height of 40.00 meters.',
    tags: ['powered', 'telescopic boom lift', 'Genie', '40.00m'],
    altText: 'Genie SX125 powered telescopic boom lift'
  },
  {
    name: '1350SJP',
    vehicleType: 'זרוע טלסקופית ישרה',
    engType: 'ממונע',
    workLocation: 'פתוח',
    workHeight: '43.00',
    liftStrenght: '0.227',
    liftAccesibility: '24.38',
    accessibility: 'הכל',
    groundType: 'הכל',
    groundLevel: 'שטח מפולס ישר',
    brand: 'JLG',
    color: '#ff773d',
    image: image1350,
    pdfLink: 'https://www.ofeklift.com/images/pdf/product_catalog/1350SJP.pdf',
    description: 'JLG 1350SJP powered telescopic boom lift, designed for extreme height tasks with a work height of 43.00 meters.',
    tags: ['powered', 'telescopic boom lift', 'JLG', '43.00m'],
    altText: 'JLG 1350SJP powered telescopic boom lift'
  }
];

export default VData;
